language: r

install:
    - Rscript -e 'install.packages(c("devtools", "testthat", "geiger", "PBD", "deSolve"))'
    - Rscript -e 'devtools::install_github("klmr/modules")'

notifications:
  slack: bigbiodiversity:2ahk1Y54AixO4hIsX5QXTPnK
  email: false

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

sudo: required

latex: false

script: make tests

after_failure:
    - ./travis-tool.sh dump_logs
