language: r
cache: packages

notifications:
  slack: bigbiodiversity:2ahk1Y54AixO4hIsX5QXTPnK

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

sudo: required

script: ./travis-tool.sh run_tests

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_deps

after_failure:
    - ./travis-tool.sh dump_logs
