language: r
cache: packages

script: ./travis-tool.sh run_tests

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh

install:
    - ./travis-tool.sh install_deps
